name: CI
on: [push]
jobs:
    build:
        name: Format on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['22.x']
                os: [ubuntu-latest] #, windows-latest, macOS-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}

            - name: Installing NPM dependencies
              run: npm ci --prefer-offline --no-audit

            - name: Format
              run: npm run format
